### ISSUE TITLE
ReleaseDLL compiling failed

### ISSUE THREAD

**Issue by UMU618** [ShiftMediaProject/nettle#1]
Project: libhogweed, Configuration: ReleaseDLL x64

> 1>ecc-192.obj : error LNK2001: unresolved external symbol nettle_ecc_192_modp
> 1>ecc-224.obj : error LNK2001: unresolved external symbol nettle_ecc_224_modp
> 1>ecc-25519.obj : error LNK2001: unresolved external symbol nettle_ecc_25519_modp
> 1>ecc-256.obj : error LNK2001: unresolved external symbol nettle_ecc_256_redc
> 1>ecc-384.obj : error LNK2001: unresolved external symbol nettle_ecc_384_modp
> 1>ecc-521.obj : error LNK2001: unresolved external symbol nettle_ecc_521_modp
> 1>E:\git\projects\github.com\ShiftMediaProject\nettle-nettle_3.3_release_20161001-2
> 
> hogweed.dll : fatal error LNK1120: 6 unresolved externals
>

**Comment by Sibras** [comment]
This should have already been fixed, make sure you update your repository to the latest and try it again.
