### ISSUE TITLE
x64 compile error

### ISSUE THREAD

**Issue by yzf888** [ShiftMediaProject/nettle#4]
x64 debug build, YASM return  -1073741819
## Context

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\yasm.targets(50,5): error MSB3721: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\"yasm.exe -Xvc -f win64 -o "S:\f\dev\ShiftMediaProject\ffmpeg\SMP\obj\Debug\x64\libnettle\memxor3.obj" -g cv8 -rraw -pgas  "S:\f\dev\ShiftMediaProject\nettle\SMP\x86_64\memxor3.s"" exited with code -1073741819.
1>Done building project "libnettle.vcxproj" -- FAILED.
## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used: master
* Operating System and Version: win10
* Compiler and Version(s): vs2019

**Comment by Sibras** [comment]
I cant reproduce that error. Most likely your yasm is not installed correctly. In fact looking at the yasm command it is missing a '\' at the end of the yasm folder suggesting you installed vsyasm using the manual method and did it incorrectly (the readme specifically mentions not to forget the trailing '\').

For future reference you should just use the supplied install script to do everything automatically.

**Comment by yzf888** [comment]
But it is ok when build x86. I rename yasm-1.3.0-win64.exe to yasm.exe and copy to VC DIR. It also ok when build other  projects in ffmpeg_deps.sln.

**Comment by Sibras** [comment]
In that case you should try using the yasm.exe that comes with VSYASM as that has additional fixes for errors.

**Comment by Sibras** [comment]
FYI If you just use the install_script.bat file and run it as administrator then it will do everything correctly for you. The manual installation is only necessary when the automatic installation fails.

**Comment by yzf888** [comment]
It is return use install_script.bat.

Detected 64 bit system...
Downloading required vswhere release binary...
Visual Studio 2019 environment detected...
Error: Invalid VS install location detected!
Error: Failed to detect VS installations using vswhere!
   Now trying fallback detection...
Error: Could not find valid Visual Studio installation!

**Comment by Sibras** [comment]
Which version of the VSYASM are you using?

**Comment by yzf888** [comment]
0.6

**Comment by Sibras** [comment]
The install_script log you pasted above seems to be for the 0.5 version, try downloading the 0.6 version again and trying that and pasting the output from that.
