### ISSUE TITLE
Nettle 3.9 #includes "sm4.h" but doesn't provide it

### ISSUE THREAD

**Issue by kbarnes3** [ShiftMediaProject/nettle#6]
## Context
Between tags 3.8 and 3.9, `nettle/gcm.h` added an `#include "sm4.h"` line. However, this file isn't copied to include\nettle. Projects that `#include "nettle/gcm.h"` will fail to build because of this missing include. The SMP version of gnutls includes gcm.h so it fails to compile with an error about missing sm4.h. 

## Expected Behavior
Headers should be able to be included cleanly

## Actual Behavior
gcm.h can't be included in other projects

## Steps to Reproduce
1.  Build x64 release version of Nettle from tag 3.9 or master
2.  Build other dependencies for gnutls
3.  Try to build x64 of gnutls from master
4.  Observe compile error

## Your Environment
* Version Used: Nettle 3.9 or master
* Operating System and Version: Windows 11
* Compiler and Version(s): Visual Studio 2022

## Possible Fix
I believe the fix would be to extend libnettle.vcxproj to copy more headers in the include directory.

**Comment by Sibras** [comment]
Fixed in nettle_3.9_release_20230514-1
